variables:
  MINIO_ACCESS_KEY: 'minioadmin'
  MINIO_SECRET_KEY: 'minioadmin'
  MINIO_URL: '172.17.0.1:9000'
  MINIO_SECURE: 'false'
  REDIS_HOST: 'cache'
  REDIS_PORT: '6379'
  REDIS_PASSWORD: 'eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81'
  MYSQL_URI: 'mysqldb://root:password@mysql:3306'
  MYSQL_DATABASE: 'ezprompt'
  PYTHONPATH: '$CI_PROJECT_DIR/backend:$PYTHONPATH'

stages:
  - test
  - build

frontend-unit-test:
  stage: test
  image: harbor.emotibot.com/emotimage/node:lts-alpine
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run test:unit
    - echo "Unit Test DONE..."
  only:
    - master
  tags:
    - adamwang

backend-lint-test:
  stage: test
  image: harbor.emotibot.com/emotimage/python:3.10
  before_script:
    - pip3 install flake8
  script:
    - flake8 $CI_PROJECT_DIR/backend
  only:
    - master
  tags:
    - adamwang

backend-unit-test:
  stage: test
  image: harbor.emotibot.com/emotimage/python:3.10
  before_script:
    - .gitlab-ci/install.sh
  script:
    - sleep 1
    - pytest backend/tests/test_unit.py 
  only:
    - master
  tags:
    - adamwang

backend-integration-test:
  stage: test
  image: harbor.emotibot.com/emotimage/python:3.10
  before_script:
    - .gitlab-ci/install.sh
  script:
    - sleep 1
    - pytest backend/tests/test_integration.py 
  only:
    - master
  tags:
    - adamwang

build:
  stage: build
  script:
      - cd docker
      - DOCKERFILE_DIR=$(cd `dirname $0`; pwd)
      - REPO_DIR=$(dirname "$DOCKERFILE_DIR")
      - DOCKERFILE_NAME='frontend'
      - tag=`git rev-parse --short HEAD`-$(date "+%Y%m%d-%H%M")
      - docker build -t harbor.emotibot.com/emotimage/ezpmt-frontend:$tag -f $DOCKERFILE_DIR/$DOCKERFILE_NAME $REPO_DIR
      - docker push harbor.emotibot.com/emotimage/ezpmt-frontend:$tag
      - DOCKERFILE_NAME='backend'
      - docker build -t harbor.emotibot.com/emotimage/ezpmt-backend:$tag -f $DOCKERFILE_DIR/$DOCKERFILE_NAME $REPO_DIR
      - docker push harbor.emotibot.com/emotimage/ezpmt-backend:$tag
  only:
      - master
  tags:
    - adamwang_shell
