stages:
  - test
  - build

frontend-unit-test:
  stage: test
  image: harbor.emotibot.com/emotimage/node:lts-alpine
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run test:unit
    - echo "Unit Test DONE..."
  only:
    - master
  tags:
    - adamwang

backend-unit-test:
  stage: test
  image: harbor.emotibot.com/emotimage/python:3.10
  before_script:
    - ./.gitlab-ci/install.sh
  script:
    - sleep 1
    - export PYTHONPATH=$CI_PROJECT_DIR/backend:$PYTHONPATH
    - pytest backend/tests/test_unit.py 
  only:
    - master
  tags:
    - adamwang

backend-integration-test:
  stage: test
  image: harbor.emotibot.com/emotimage/python:3.10
  before_script:
    - ./.gitlab-ci/install.sh
  script:
    - sleep 1
    - export PYTHONPATH=$CI_PROJECT_DIR/backend:$PYTHONPATH
    - pytest backend/tests/test_integration.py 
  only:
    - master
  tags:
    - adamwang

build:
  image: docker:20.10.2
  stage: build
  before_script:
      - pip3 install docker-compose
      - docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  script:
      - make build
      - make push
  only:
      - master