stages:
  - test

frontend_test:
  stage: test
  image: harbor.emotibot.com/emotimage/node:lts-alpine
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run test:unit
    - echo "Unit Test DONE..."
  only:
    - master
  tags:
    - adamwang