version: '3'
services:
  frontend:
    image: harbor.emotibot.com/emotimage/ezpmt-frontend:${IMAGE_TAG}
    build:
        context: ./
        dockerfile: ./docker/frontend
    volumes:
      - ./frontend:/workspace
    ports:
        - 8080:8080
  backend:
    image: harbor.emotibot.com/emotimage/ezpmt-backend:${IMAGE_TAG}
    build:
        context: ./
        dockerfile: ./docker/backend
    volumes:
      - ./backend:/workspace
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_URL=172.17.0.1:9000
      - MINIO_SECURE=false
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
        - 8877:8877
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./backend/minio/data:/data
    restart: always    
    environment:
        MINIO_USER: minioadmin
        MINIO_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./backend/cache:/data
