version: '3'
services:
  frontend:
    image: harbor.emotibot.com/emotimage/ezpmt-frontend:${IMAGE_TAG}
    build:
        context: ./
        dockerfile: ./docker/frontend
    volumes:
      - ./frontend:/workspace
    ports:
        - 8080:8080
  backend:
    image: harbor.emotibot.com/emotimage/ezpmt-backend:${IMAGE_TAG}
    build:
        context: ./
        dockerfile: ./docker/backend
    volumes:
      - ./backend:/workspace
    environment:
      - CONCURRENT_JOBS=6
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_URL=172.17.0.1:9000
      - MINIO_SECURE=false
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - MYSQL_URI=mysql+pymysql://root:password@mysql:3306
      - MYSQL_DATABASE=ezprompt
      - F_INTERNAL_IP=192.168.3.16:8087
      - F_EXTERNAL_IP=61.216.75.236:8087
      - B_INTERNAL_IP=192.168.3.16:9527
      - B_EXTERNAL_IP=61.216.75.236:9528
      - PROXY_IP=192.168.3.16:9999
      - BUILD_VERSION=${BUILD_VERSION}
    ports:
        - 9527:9527
  minio:
    image: harbor.emotibot.com/emotimage/minio:RELEASE.2023-02-17T17-52-43Z
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    restart: always
    volumes:
      - ./backend/minio/data:/data  
    environment:
        MINIO_USER: minioadmin
        MINIO_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
  cache:
    image: harbor.emotibot.com/emotimage/redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./backend/cache:/data
  mysql:
    image: harbor.emotibot.com/emotimage/mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./backend/utils/sql_init:/docker-entrypoint-initdb.d
      - ./backend/mysql:/var/lib/mysql
      - ./backend/utils/mysqld:/var/run/mysqld
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: password
      TZ: UTC
      MYSQLD__wait_timeout: 86400
      MYSQLD__interactive_timeout: 86400
  midjourney-proxy:
    image: chazzcheung/midjourney-proxy:latest
    environment:
      - mj.discord.guild-id=1115834541643403284
      - mj.discord.channel-id=1115834541643403287
      - mj.discord.user-token=MTA4MTA0MjM4MjQ3NDE4Mjc2OQ.Gn5kNJ.DGv6QNmaQtf8NoRHwDKe97yA3roysbCwdl24Dw
    restart: always
    ports:
      - 9999:8080
  midjourney-proxy2:
    image: chazzcheung/midjourney-proxy:latest
    environment:
      - mj.discord.guild-id=1115834494818209844
      - mj.discord.channel-id=1115834495313117216
      - mj.discord.user-token=MTExNTE3MjE4Nzc4ODI5MjE1Ng.G7IU23.nxS4oYHlQkqIohYzuiMa5E4FyXfpWofcB2D2a4
    restart: always
    ports:
      - 9998:8080  
  # nginx:
  #   container_name: nginx
  #   build:
  #       context: ./
  #       dockerfile: ./docker/nginx
  #   ports:
  #     - 8087:80
  #   restart: always
  #   volumes:
  #     - ./frontend/dist:/usr/share/nginx/html
  #   depends_on:
  #     - frontend
  #     - backend
  #     - minio
  #     - cache
  #     - mysql
