version: '3'
services:
  frontend:
    image: harbor.emotibot.com/emotimage/ezpmt-frontend:${IMAGE_TAG}
    build:
        context: ./
        dockerfile: ./docker/frontend
    volumes:
      - ./frontend:/workspace
    ports:
        - 8080:8080
  backend:
    image: harbor.emotibot.com/emotimage/ezpmt-backend:${IMAGE_TAG}
    build:
        context: ./
        dockerfile: ./docker/backend
    volumes:
      - ./backend:/workspace
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_URL=172.17.0.1:9000
      - MINIO_SECURE=false
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - MYSQL_URI=mysql+pymysql://root:password@mysql:3306
      - MYSQL_DATABASE=ezprompt
      - IP=192.168.2.16
      - proxy=20.6.72.133:8080
      - mj-api-secret=Biscuit007
    ports:
        - 9527:9527
  minio:
    image: harbor.emotibot.com/emotimage/minio:RELEASE.2023-02-17T17-52-43Z
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    restart: always
    volumes:
      - ./backend/minio/data:/data  
    environment:
        MINIO_USER: minioadmin
        MINIO_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
  cache:
    image: harbor.emotibot.com/emotimage/redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./backend/cache:/data
  mysql:
    image: harbor.emotibot.com/emotimage/mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./backend/utils/sql_init:/docker-entrypoint-initdb.d
      - ./backend/mysql:/var/lib/mysql
      - ./backend/utils/mysqld:/var/run/mysqld
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: password
      TZ: UTC
      MYSQLD__wait_timeout: 86400
      MYSQLD__interactive_timeout: 86400
  # nginx:
  #   container_name: nginx
  #   build:
  #       context: ./
  #       dockerfile: ./docker/nginx
  #   ports:
  #     - 8087:80
  #   restart: always
  #   volumes:
  #     - ./frontend/dist:/usr/share/nginx/html
  #   depends_on:
  #     - frontend
  #     - backend
  #     - minio
  #     - cache
  #     - mysql
