version: '3'
services:
  app:
    image: harbor.emotibot.com/image/sdxl:${IMAGE_TAG}
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/workspace
    environment:
      - WORKERS=2
      - MINIO_USER=minioadmin
      - MINIO_PASSWORD=minioadmin
    ports:
        - 8877:8877
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./minio/data:/data
    restart: always    
    environment:
        MINIO_USER: minioadmin
        MINIO_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
